create table if not exists public.users (
  user_id bigint primary key,
  age integer not null check (age > 0),
  country text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  product_id bigint primary key,
  name text not null,
  category text not null,
  price numeric(12, 2) not null check (price >= 0),
  rating numeric(3, 1) not null default 0,
  rating_count integer not null default 0,
  views integer not null default 0,
  clicks integer not null default 0,
  purchases integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  product_id bigint not null references public.products(product_id) on delete cascade,
  viewed integer not null default 0,
  clicked integer not null default 0,
  purchased integer not null default 0,
  rating integer not null default 0 check (rating between 0 and 5),
  fitness integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, product_id)
);

create index if not exists interactions_user_id_idx on public.interactions (user_id);
create index if not exists interactions_product_id_idx on public.interactions (product_id);
create index if not exists products_category_idx on public.products (category);

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.interactions enable row level security;

drop policy if exists "Public read users" on public.users;
create policy "Public read users"
on public.users
for select
using (true);

drop policy if exists "Public read products" on public.products;
create policy "Public read products"
on public.products
for select
using (true);

drop policy if exists "Public read interactions" on public.interactions;
create policy "Public read interactions"
on public.interactions
for select
using (true);

drop policy if exists "Public update products" on public.products;
create policy "Public update products"
on public.products
for update
using (true)
with check (true);

drop policy if exists "Public insert interactions" on public.interactions;
create policy "Public insert interactions"
on public.interactions
for insert
with check (true);

drop policy if exists "Public update interactions" on public.interactions;
create policy "Public update interactions"
on public.interactions
for update
using (true)
with check (true);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists touch_products_updated_at on public.products;
create trigger touch_products_updated_at
before update on public.products
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_interactions_updated_at on public.interactions;
create trigger touch_interactions_updated_at
before update on public.interactions
for each row
execute function public.touch_updated_at();
